baseurl = "/"
languageCode = "fr-fr"
title = "Super Alex , le Blog"
theme = "hugo-strata-theme"
disqusShortname = "super-alex-blog"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

enableEmoji = true
home = ["RSS"]


[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Super Alex"
	description = "Les pérégrinations d'une jeune dev !"

	# Format dates with Go's time formatting
	date_format = "02-01-2006"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.png"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Moi c'est Super Alex**, Jeune développeur en formation<br> je vous livre mes impressions<br> via ce site/blog. Enjoy"
		# The icons will be shown if you enter your username
		twitter = "StrubAlexandra"
		github = "napka4"
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = "alexandra-strub-ba1061114"

		copyright = [
			"&copy; Super Alex",
			"Design: with &hearts; in Paris",
			"Images: Super Alex ou libre de droits"
		]

	[params.about]
		hide  = false
		title = "Les aventures trépidantes d'une jeune dév !"
		content = "Jeune développeuse (sa reconversion date d'avril 2017), Super Alex avait envie d'un espace à elle pour tester, rapporter et partager ses trouvailles. Quelles soient en lien avec le développement ou non ! Alors bienvenue dans mon bac à sable !"

	[params.recentposts]
    	hide  = false
    	title = "Mes derniers blabla :"

	[params.portfolio]
		hide  = false
		title = "Ce que j'ai fait dernièrement !"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/atelierbig.jpg"
			thumb = "thumbs/ateliermin.jpg"
			title = "Atelier du Jardin 60"
			description = "Site e-commerce sous Prestashop. Développement complet de la boutique, thème de base"
			url = "http://atelierdujardin60.fr"

		[[params.portfolio.gallery]]
			image = "fulls/2rouescassbig.jpg"
			thumb = "thumbs/2rouescassmin.jpg"
			title = "2RouesCass"
			description = "Site e-commerce sous Prestashop. Développement complet de la boutique, thème de base 1.7."
			url = "http://2rouescass.com"

		[[params.portfolio.gallery]]
			image = "fulls/autrement.png"
			thumb = "thumbs/autrementmin.png"
			title = "Autrement Tapisserie"
			description = "Refonte du design sous Wordpress"
			url = "http://www.autrement-tapisserie.fr/"

		[[params.portfolio.gallery]]
			image = "fulls/gentlemenbig.png"
			thumb = "thumbs/gentlemenmin.png"
			title = "Le Salon des Gentlemen"
			description = "Réalisation complète sous Wordpress"
			url = "http://lesalondesgentlemen.fr/"

		[[params.portfolio.gallery]]
			image = "fulls/efs1.png"
			thumb = "thumbs/efs2.png"
			title = "Etablissement Français du Sang - EFS"
			description = "Mailing EFS, réalisation du mailing responsive HTML5"

		[[params.portfolio.gallery]]
			image = "fulls/eviaudio.png"
			thumb = "thumbs/eviaudio.png"
			title = "EVI AUDIO"
			description = "Mise à jour du site, maintenance sur Joomla"
			url = "http://www.eviaudio.fr/"

		[[params.portfolio.gallery]]
            image = "fulls/imprimbig.png"
            thumb = "thumbs/annonce-site.png"
            title = "Imprim'Luxe"
            description = "Refonte totale du site (avec l'aide de graphistes!), Développement spécifique sur le moteur de recherche interne, Réalisation complète sous WordPress, Mise à jour du site, maintenance sur WordPress"
            url = "http://www.imprim-luxe.fr/"

		[[params.portfolio.gallery]]
        	image = "fulls/750.jpg"
        	thumb = "thumbs/250.jpg"
            title = "Groupe Adine"
            description = "Refonte totale du site (avec l'aide de graphistes!), Développement spécifique sur la version desktop et tablette (multiscroll), Réalisation complète sous WordPress, Mise à jour du site, maintenance sur WordPress"
            url = "http://groupe-adine.com/"

	[params.contact]
		hide  = false
		title = "Tu veux me contacter ?"
		content = "C'est facile, remplit ce questionnaire, et je te répondrais !"

		address = [
			"18 rue Demarquay",
			"75010 Paris",
			"FRANCE"
		]
		phone = "06-80-41-78-75"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "nanshee4@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Nom"
			email = "Email"
			message = "Message"
			submit = "Envoyer ce message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "Mon parcours"
	identifier = "timeline"
	url  = "/timeline/"
	weight = 5

[[menu.main]]
	name = "Blog"
	url  = "/post/"
	weight = 10

[[menu.main]]
	name = "Services"
	url  = "/service/"
	weight = 15